version: '3.8'

services:
  app:
    build: .
    ports: ["8080:8080"]
    environment:
      # 스프링이 자동으로 인식하는 표준 이름으로 교체
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      # 이건 커스텀 변수이므로 소스 코드 내에서 ${STOCK_KEY} 등으로 사용 중이어야 합니다.
      STOCK_KEY: ${STOCK_KEY}
      STOCK_SECRET: ${STOCK_SECRET}
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      #MYSQL_USER: ${DB_USER}
      #MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: